-- Ontara deterministic RAW -> CORE refresh
--
-- Purpose:
--   1. Reload the deterministic staged CSV dataset into RAW.
--   2. Convert source-preserving VARCHAR values into governed CORE types.
--   3. Produce explicit row-count evidence for both layers.
--
-- This script is intentionally rerunnable:
--   - RAW tables are truncated before COPY.
--   - CORE tables are truncated before typed inserts.
--   - COPY aborts on malformed input.
--
-- Expected deterministic row counts:
--   suppliers             8
--   parts                12
--   plants                4
--   supplier_parts       23
--   purchase_orders      24
--   customers            10
--   customer_orders      30
--   shipments            32
--   shipment_events     192
--   inventory_snapshots  48


USE ROLE ONTARA_DEV_ROLE;
USE WAREHOUSE ONTARA_WH;
USE DATABASE ONTARA;


-- ===========================================================================
-- PHASE 1: RESET RAW
-- ===========================================================================

TRUNCATE TABLE ONTARA.RAW.SUPPLIERS;
TRUNCATE TABLE ONTARA.RAW.PARTS;
TRUNCATE TABLE ONTARA.RAW.PLANTS;
TRUNCATE TABLE ONTARA.RAW.SUPPLIER_PARTS;
TRUNCATE TABLE ONTARA.RAW.PURCHASE_ORDERS;
TRUNCATE TABLE ONTARA.RAW.CUSTOMERS;
TRUNCATE TABLE ONTARA.RAW.CUSTOMER_ORDERS;
TRUNCATE TABLE ONTARA.RAW.SHIPMENTS;
TRUNCATE TABLE ONTARA.RAW.SHIPMENT_EVENTS;
TRUNCATE TABLE ONTARA.RAW.INVENTORY_SNAPSHOTS;


-- ===========================================================================
-- PHASE 2: LOAD DETERMINISTIC CSV FILES INTO RAW
-- ===========================================================================

COPY INTO ONTARA.RAW.SUPPLIERS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/suppliers.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.PARTS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/parts.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.PLANTS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/plants.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.SUPPLIER_PARTS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/supplier_parts.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.PURCHASE_ORDERS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/purchase_orders.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.CUSTOMERS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/customers.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.CUSTOMER_ORDERS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/customer_orders.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.SHIPMENTS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/shipments.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.SHIPMENT_EVENTS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/shipment_events.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO ONTARA.RAW.INVENTORY_SNAPSHOTS
FROM @ONTARA.RAW.SYNTHETIC_STAGE/inventory_snapshots.csv.gz
FILE_FORMAT = (FORMAT_NAME = 'ONTARA.RAW.ONTARA_CSV_FORMAT')
ON_ERROR = 'ABORT_STATEMENT';


-- ===========================================================================
-- PHASE 3: VERIFY RAW ROW COUNTS
-- ===========================================================================

SELECT 'SUPPLIERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM ONTARA.RAW.SUPPLIERS

UNION ALL

SELECT 'PARTS', COUNT(*)
FROM ONTARA.RAW.PARTS

UNION ALL

SELECT 'PLANTS', COUNT(*)
FROM ONTARA.RAW.PLANTS

UNION ALL

SELECT 'SUPPLIER_PARTS', COUNT(*)
FROM ONTARA.RAW.SUPPLIER_PARTS

UNION ALL

SELECT 'PURCHASE_ORDERS', COUNT(*)
FROM ONTARA.RAW.PURCHASE_ORDERS

UNION ALL

SELECT 'CUSTOMERS', COUNT(*)
FROM ONTARA.RAW.CUSTOMERS

UNION ALL

SELECT 'CUSTOMER_ORDERS', COUNT(*)
FROM ONTARA.RAW.CUSTOMER_ORDERS

UNION ALL

SELECT 'SHIPMENTS', COUNT(*)
FROM ONTARA.RAW.SHIPMENTS

UNION ALL

SELECT 'SHIPMENT_EVENTS', COUNT(*)
FROM ONTARA.RAW.SHIPMENT_EVENTS

UNION ALL

SELECT 'INVENTORY_SNAPSHOTS', COUNT(*)
FROM ONTARA.RAW.INVENTORY_SNAPSHOTS

ORDER BY TABLE_NAME;


-- ===========================================================================
-- PHASE 4: RESET CORE
-- ===========================================================================

TRUNCATE TABLE ONTARA.CORE.SHIPMENT_EVENTS;
TRUNCATE TABLE ONTARA.CORE.SHIPMENTS;
TRUNCATE TABLE ONTARA.CORE.INVENTORY_SNAPSHOTS;
TRUNCATE TABLE ONTARA.CORE.CUSTOMER_ORDERS;
TRUNCATE TABLE ONTARA.CORE.PURCHASE_ORDERS;
TRUNCATE TABLE ONTARA.CORE.SUPPLIER_PARTS;
TRUNCATE TABLE ONTARA.CORE.CUSTOMERS;
TRUNCATE TABLE ONTARA.CORE.PLANTS;
TRUNCATE TABLE ONTARA.CORE.PARTS;
TRUNCATE TABLE ONTARA.CORE.SUPPLIERS;


-- ===========================================================================
-- PHASE 5: GOVERNED TYPE CONVERSION INTO CORE
-- ===========================================================================


-- Supplier

INSERT INTO ONTARA.CORE.SUPPLIERS (
    SUPPLIER_ID,
    SUPPLIER_NAME,
    COUNTRY_CODE,
    RISK_TIER,
    STATUS
)
SELECT
    SUPPLIER_ID,
    SUPPLIER_NAME,
    COUNTRY_CODE,
    RISK_TIER,
    STATUS
FROM ONTARA.RAW.SUPPLIERS;


-- Part

INSERT INTO ONTARA.CORE.PARTS (
    PART_ID,
    PART_NAME,
    CATEGORY,
    UNIT_OF_MEASURE,
    STANDARD_UNIT_COST_USD
)
SELECT
    PART_ID,
    PART_NAME,
    CATEGORY,
    UNIT_OF_MEASURE,
    TO_DECIMAL(STANDARD_UNIT_COST_USD, 18, 2)
FROM ONTARA.RAW.PARTS;


-- Plant

INSERT INTO ONTARA.CORE.PLANTS (
    PLANT_ID,
    PLANT_NAME,
    COUNTRY_CODE,
    REGION,
    CAPACITY_CLASS
)
SELECT
    PLANT_ID,
    PLANT_NAME,
    COUNTRY_CODE,
    REGION,
    CAPACITY_CLASS
FROM ONTARA.RAW.PLANTS;


-- Supplier -> Part relationship

INSERT INTO ONTARA.CORE.SUPPLIER_PARTS (
    SUPPLIER_ID,
    PART_ID,
    LEAD_TIME_DAYS,
    CONTRACTED_UNIT_COST_USD,
    MINIMUM_ORDER_QUANTITY,
    PRIMARY_SUPPLIER_FLAG
)
SELECT
    SUPPLIER_ID,
    PART_ID,
    TO_NUMBER(LEAD_TIME_DAYS, 18, 0),
    TO_DECIMAL(CONTRACTED_UNIT_COST_USD, 18, 2),
    TO_NUMBER(MINIMUM_ORDER_QUANTITY, 18, 0),
    TO_BOOLEAN(PRIMARY_SUPPLIER_FLAG)
FROM ONTARA.RAW.SUPPLIER_PARTS;


-- Purchase Orders

INSERT INTO ONTARA.CORE.PURCHASE_ORDERS (
    PURCHASE_ORDER_ID,
    SUPPLIER_ID,
    PLANT_ID,
    PART_ID,
    ORDER_DATE,
    PROMISED_DELIVERY_DATE,
    ORDERED_UNITS,
    RECEIVED_UNITS,
    UNIT_PURCHASE_COST_USD,
    FREIGHT_COST_USD,
    DUTY_COST_USD,
    HANDLING_COST_USD,
    STATUS
)
SELECT
    PURCHASE_ORDER_ID,
    SUPPLIER_ID,
    PLANT_ID,
    PART_ID,
    TO_DATE(ORDER_DATE),
    TO_DATE(PROMISED_DELIVERY_DATE),
    TO_NUMBER(ORDERED_UNITS, 18, 0),
    TO_NUMBER(RECEIVED_UNITS, 18, 0),
    TO_DECIMAL(UNIT_PURCHASE_COST_USD, 18, 2),
    TO_DECIMAL(FREIGHT_COST_USD, 18, 2),
    TO_DECIMAL(DUTY_COST_USD, 18, 2),
    TO_DECIMAL(HANDLING_COST_USD, 18, 2),
    STATUS
FROM ONTARA.RAW.PURCHASE_ORDERS;


-- Customer

INSERT INTO ONTARA.CORE.CUSTOMERS (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    COUNTRY_CODE,
    PRIORITY_TIER
)
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    SEGMENT,
    COUNTRY_CODE,
    PRIORITY_TIER
FROM ONTARA.RAW.CUSTOMERS;


-- Customer Orders

INSERT INTO ONTARA.CORE.CUSTOMER_ORDERS (
    ORDER_ID,
    CUSTOMER_ID,
    PLANT_ID,
    PART_ID,
    ORDER_DATE,
    PROMISED_SHIP_DATE,
    ORDERED_UNITS,
    FULFILLED_UNITS,
    UNIT_SALE_PRICE_USD,
    STATUS
)
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    PLANT_ID,
    PART_ID,
    TO_DATE(ORDER_DATE),
    TO_DATE(PROMISED_SHIP_DATE),
    TO_NUMBER(ORDERED_UNITS, 18, 0),
    TO_NUMBER(FULFILLED_UNITS, 18, 0),
    TO_DECIMAL(UNIT_SALE_PRICE_USD, 18, 2),
    STATUS
FROM ONTARA.RAW.CUSTOMER_ORDERS;


-- Shipments

INSERT INTO ONTARA.CORE.SHIPMENTS (
    SHIPMENT_ID,
    SHIPMENT_TYPE,
    PURCHASE_ORDER_ID,
    CUSTOMER_ORDER_ID,
    PART_ID,
    PLANT_ID,
    SUPPLIER_ID,
    CUSTOMER_ID,
    SHIP_DATE,
    PROMISED_DELIVERY_DATE,
    ACTUAL_DELIVERY_DATE,
    SHIPPED_UNITS,
    CARRIER,
    STATUS
)
SELECT
    SHIPMENT_ID,
    SHIPMENT_TYPE,
    PURCHASE_ORDER_ID,
    CUSTOMER_ORDER_ID,
    PART_ID,
    PLANT_ID,
    SUPPLIER_ID,
    CUSTOMER_ID,
    TO_DATE(SHIP_DATE),
    TO_DATE(PROMISED_DELIVERY_DATE),
    TO_DATE(ACTUAL_DELIVERY_DATE),
    TO_NUMBER(SHIPPED_UNITS, 18, 0),
    CARRIER,
    STATUS
FROM ONTARA.RAW.SHIPMENTS;


-- Shipment Events

INSERT INTO ONTARA.CORE.SHIPMENT_EVENTS (
    SHIPMENT_EVENT_ID,
    SHIPMENT_ID,
    EVENT_SEQUENCE,
    EVENT_TYPE,
    EVENT_TIMESTAMP,
    LOCATION_CODE,
    DELAY_REASON,
    SOURCE_SYSTEM
)
SELECT
    SHIPMENT_EVENT_ID,
    SHIPMENT_ID,
    TO_NUMBER(EVENT_SEQUENCE, 18, 0),
    EVENT_TYPE,
    TO_TIMESTAMP_NTZ(EVENT_TIMESTAMP),
    LOCATION_CODE,
    DELAY_REASON,
    SOURCE_SYSTEM
FROM ONTARA.RAW.SHIPMENT_EVENTS;


-- Inventory Snapshots

INSERT INTO ONTARA.CORE.INVENTORY_SNAPSHOTS (
    SNAPSHOT_DATE,
    PLANT_ID,
    PART_ID,
    ON_HAND_UNITS,
    ALLOCATED_UNITS,
    IN_TRANSIT_UNITS,
    SAFETY_STOCK_UNITS,
    AVG_DAILY_DEMAND_UNITS
)
SELECT
    TO_DATE(SNAPSHOT_DATE),
    PLANT_ID,
    PART_ID,
    TO_NUMBER(ON_HAND_UNITS, 18, 0),
    TO_NUMBER(ALLOCATED_UNITS, 18, 0),
    TO_NUMBER(IN_TRANSIT_UNITS, 18, 0),
    TO_NUMBER(SAFETY_STOCK_UNITS, 18, 0),
    TO_DECIMAL(AVG_DAILY_DEMAND_UNITS, 18, 2)
FROM ONTARA.RAW.INVENTORY_SNAPSHOTS;


-- ===========================================================================
-- PHASE 6: VERIFY GOVERNED CORE ROW COUNTS
-- ===========================================================================

SELECT 'SUPPLIERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT
FROM ONTARA.CORE.SUPPLIERS

UNION ALL

SELECT 'PARTS', COUNT(*)
FROM ONTARA.CORE.PARTS

UNION ALL

SELECT 'PLANTS', COUNT(*)
FROM ONTARA.CORE.PLANTS

UNION ALL

SELECT 'SUPPLIER_PARTS', COUNT(*)
FROM ONTARA.CORE.SUPPLIER_PARTS

UNION ALL

SELECT 'PURCHASE_ORDERS', COUNT(*)
FROM ONTARA.CORE.PURCHASE_ORDERS

UNION ALL

SELECT 'CUSTOMERS', COUNT(*)
FROM ONTARA.CORE.CUSTOMERS

UNION ALL

SELECT 'CUSTOMER_ORDERS', COUNT(*)
FROM ONTARA.CORE.CUSTOMER_ORDERS

UNION ALL

SELECT 'SHIPMENTS', COUNT(*)
FROM ONTARA.CORE.SHIPMENTS

UNION ALL

SELECT 'SHIPMENT_EVENTS', COUNT(*)
FROM ONTARA.CORE.SHIPMENT_EVENTS

UNION ALL

SELECT 'INVENTORY_SNAPSHOTS', COUNT(*)
FROM ONTARA.CORE.INVENTORY_SNAPSHOTS

ORDER BY TABLE_NAME;


-- ===========================================================================
-- PHASE 7: CONTROLLED SCENARIO SMOKE TEST
-- ===========================================================================

SELECT
    s.SUPPLIER_ID,
    s.SUPPLIER_NAME,
    s.RISK_TIER,
    s.STATUS AS SUPPLIER_STATUS,
    sp.PART_ID,
    p.PART_NAME,
    co.PLANT_ID,
    co.ORDER_ID,
    co.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.PRIORITY_TIER,
    co.ORDERED_UNITS,
    co.FULFILLED_UNITS
FROM ONTARA.CORE.SUPPLIERS s
JOIN ONTARA.CORE.SUPPLIER_PARTS sp
    ON sp.SUPPLIER_ID = s.SUPPLIER_ID
JOIN ONTARA.CORE.PARTS p
    ON p.PART_ID = sp.PART_ID
JOIN ONTARA.CORE.CUSTOMER_ORDERS co
    ON co.PART_ID = sp.PART_ID
JOIN ONTARA.CORE.CUSTOMERS c
    ON c.CUSTOMER_ID = co.CUSTOMER_ID
WHERE s.SUPPLIER_ID = 'SUP-003'
  AND sp.PART_ID = 'PRT-009'
  AND co.PLANT_ID = 'PLT-003'
  AND co.ORDER_ID = 'ORD-008'
  AND c.CUSTOMER_ID = 'CUS-003';