-- Ontara operational CDC pipeline.
--
-- Incremental Dynamic Table
--   -> standard Stream
--   -> conditional scheduled Task
--   -> persistent operational change history.

USE ROLE ONTARA_DEV_ROLE;
USE WAREHOUSE ONTARA_WH;
USE DATABASE ONTARA;

CREATE TABLE IF NOT EXISTS ONTARA.GOVERNANCE.SUPPLY_HEALTH_CHANGE_LOG (
    CHANGE_ID VARCHAR NOT NULL,
    HEALTH_KEY VARCHAR NOT NULL,

    SUPPLIER_ID VARCHAR,
    PART_ID VARCHAR,
    PLANT_ID VARCHAR,
    ORDER_ID VARCHAR,
    CUSTOMER_ID VARCHAR,

    OUTSTANDING_ORDER_UNITS NUMBER,
    OUTSTANDING_REVENUE_EXPOSURE_USD NUMBER(18,2),

    AVAILABLE_INVENTORY_UNITS NUMBER,
    SAFETY_STOCK_UNITS NUMBER,
    INVENTORY_SHORTFALL_TO_SAFETY_UNITS NUMBER,
    DAYS_OF_INVENTORY NUMBER(18,2),

    ACTIVE_ALTERNATE_SUPPLIER_COUNT NUMBER,

    IMPACT_RISK_SCORE NUMBER,
    IMPACT_RISK_BAND VARCHAR,
    OPERATIONAL_HEALTH_STATUS VARCHAR,
    RECOMMENDED_RESPONSE VARCHAR,

    STREAM_ACTION VARCHAR NOT NULL,
    STREAM_IS_UPDATE BOOLEAN NOT NULL,
    STREAM_ROW_ID VARCHAR,

    SOURCE_OBJECT VARCHAR NOT NULL,
    CAPTURED_AT TIMESTAMP_LTZ NOT NULL
);

CREATE OR REPLACE STREAM ONTARA.GOVERNANCE.SUPPLY_HEALTH_STREAM
    ON DYNAMIC TABLE ONTARA.SEMANTIC.OPERATIONAL_SUPPLY_HEALTH
;

CREATE OR REPLACE TASK ONTARA.GOVERNANCE.PROCESS_SUPPLY_HEALTH_CHANGES
    WAREHOUSE = ONTARA_WH
    SCHEDULE = '1 MINUTE'
    COMMENT = 'Consume operational supply-health CDC only when stream data exists.'
    WHEN SYSTEM$STREAM_HAS_DATA(
        'ONTARA.GOVERNANCE.SUPPLY_HEALTH_STREAM'
    )
AS
INSERT INTO ONTARA.GOVERNANCE.SUPPLY_HEALTH_CHANGE_LOG (
    CHANGE_ID,
    HEALTH_KEY,
    SUPPLIER_ID,
    PART_ID,
    PLANT_ID,
    ORDER_ID,
    CUSTOMER_ID,
    OUTSTANDING_ORDER_UNITS,
    OUTSTANDING_REVENUE_EXPOSURE_USD,
    AVAILABLE_INVENTORY_UNITS,
    SAFETY_STOCK_UNITS,
    INVENTORY_SHORTFALL_TO_SAFETY_UNITS,
    DAYS_OF_INVENTORY,
    ACTIVE_ALTERNATE_SUPPLIER_COUNT,
    IMPACT_RISK_SCORE,
    IMPACT_RISK_BAND,
    OPERATIONAL_HEALTH_STATUS,
    RECOMMENDED_RESPONSE,
    STREAM_ACTION,
    STREAM_IS_UPDATE,
    STREAM_ROW_ID,
    SOURCE_OBJECT,
    CAPTURED_AT
)
SELECT
    UUID_STRING(),
    HEALTH_KEY,
    SUPPLIER_ID,
    PART_ID,
    PLANT_ID,
    ORDER_ID,
    CUSTOMER_ID,
    OUTSTANDING_ORDER_UNITS,
    OUTSTANDING_REVENUE_EXPOSURE_USD,
    AVAILABLE_INVENTORY_UNITS,
    SAFETY_STOCK_UNITS,
    INVENTORY_SHORTFALL_TO_SAFETY_UNITS,
    DAYS_OF_INVENTORY,
    ACTIVE_ALTERNATE_SUPPLIER_COUNT,
    IMPACT_RISK_SCORE,
    IMPACT_RISK_BAND,
    OPERATIONAL_HEALTH_STATUS,
    RECOMMENDED_RESPONSE,
    METADATA$ACTION,
    METADATA$ISUPDATE,
    METADATA$ROW_ID,
    'ONTARA.SEMANTIC.OPERATIONAL_SUPPLY_HEALTH',
    CURRENT_TIMESTAMP()
FROM ONTARA.GOVERNANCE.SUPPLY_HEALTH_STREAM
;

ALTER TASK ONTARA.GOVERNANCE.PROCESS_SUPPLY_HEALTH_CHANGES RESUME;
